### ISSUE TITLE
Demo Site Broken

### ISSUE THREAD

**Issue by ds2-jetten** [tegonhq/tegon#137]
I saw Tegon referenced in my TLDR newsletter this morning so I wanted to check it out. Unfortunately, the demo site appears to be broken (hopefully the TLDR traffic didn't cause it). 

Here's what I am seeing in the browser:
![image](https://github.com/tegonhq/tegon/assets/105557969/a1c0602a-abee-4f71-af56-bf1d48c5f04f)

**Comment by AggManik** [comment]
Hey we took it down intentionally as there were some bad actors that were misusing the demo account by creating issues with bad language. We will figure out something and will let you know.

**Comment by AggManik** [comment]
This is fixed.
