### ISSUE TITLE
As alternative to teable.io/nocodb

### ISSUE THREAD

**Issue by vasnt** [tegonhq/tegon#138]
- does it has features like nocodb/teable projects? like various columns: multiple-selection, url etc.?

**Comment by harshithmullapudi** [comment]
Hey, no familiar with the nocodb project. May I know how is this feature used ?

**Comment by vasnt** [comment]
- nocodb is basically airtable alternative. https://nocodb.com/
- It supports several column types listed here: https://docs.nocodb.com/fields/fields-overview

**Comment by harshithmullapudi** [comment]
You want to use this to replace the postgres we are using for database?

**Comment by vasnt** [comment]
i am just wondering whether tegon supports such different kind of columns in spreadsheet/database or not

**Comment by harshithmullapudi** [comment]
We don't have the support for these yet. Also we haven't thought the direction of being an alternative to airtable/nocodb
