### ISSUE TITLE
Hybrid Label provision?

### ISSUE THREAD

**Issue by vasnt** [tegonhq/tegon#139]
https://github.com/nocodb/nocodb/issues/8885

Does it has Hybrid labels provision/possible to add such tags/labels in column?

**Comment by harshithmullapudi** [comment]
Hey could you elaborate on this ?

**Comment by vasnt** [comment]
it is basically label/tag that support text & number. 
https://github.com/teableio/teable/issues/491 detailed on this link. 
it helps to prioritize/assign ranking using number for each row with respect to its text label.

**Comment by AggManik** [comment]
Hey, I went through the teableio issue, can you help us understand how would weights in labels will help you in issue tracking. For priority we have a different field to mark the importance of the task.

**Comment by vasnt** [comment]
Hi @AggManik, each row/task in database/spreadsheet may have multiple labels/tags. e.g

- I want to go to zoo this weekend to see animals. I like big animals. 
I may tag/label above item/row/task as  Fish-5, Elephant-1 since for me, Elephant is more important than fish as far as animals are concerned in this particular line/task.  (Considering number 1 is more important/priority than number 5)

**Comment by AggManik** [comment]
Hey @vasnt i think your use-case is different from the software development issue tracking and currently we will have labels without weight only. Let us know in case you need any other help.
