### ISSUE TITLE
"docker-compose  build"  error

### ISSUE THREAD

**Issue by leemgs** [tegonhq/tegon#141]
The latest commit generates the run-time error of  the "docker-compose build" command. 

* How to reproduce this issue. 
```
invain@u2204:~/tegon$ docker-compose  build
validating /var/www/invain/tegon/docker-compose.yaml: services.server.environment array items[43,46] must be unique
```

**Comment by harshithmullapudi** [comment]
Hey this is fixed, could you confirm if it is working for you? If so I will close the issue.

**Comment by leemgs** [comment]
It's okay. Thanks.
