### ISSUE TITLE
The `tegonhq/tegon-server` image not published to DockerHub

### ISSUE THREAD

**Issue by arcastro** [tegonhq/tegon#143]
Hello,

Looks like the `tegonhq/tegon-server` image is not published to DockerHub and the docker-compose file has it built from source. 

Out of curiosity, is there a reason for this? I appreciate the help. 

Feel free to close this issue as it's not too important. 
It's just a minor hurdle when deploying to Kubernetes, rather than through Docker.

**Comment by harshithmullapudi** [comment]
Hey, we use gcloud to upload the images and that needs certs and service key json which needs to be copied on to the server container.

Currently we will have to work on writing an entry point to copy these folders from the main folder. 

This is the pending work. We should be picking this in the coming few days.

**Comment by harshithmullapudi** [comment]
Hey @arcastro we have now published tegon-server image on docker hub, also have updated the self-deployment docs.
