### ISSUE TITLE
Creating the issue Not showing up the count

### ISSUE THREAD

**Issue by ashish07-07** [tegonhq/tegon#146]
When i created a issue in my team and assigned the label , priority it did not show up in the issue created .

**Comment by harshithmullapudi** [comment]
Hey, do you see any error in the server you can use this command `docker logs <server-id>`. We use OpenAI to generate the titles https://platform.openai.com/docs/quickstart/account-setup can you use this to generate a key.  Once you generate
1. Add it to the .env
2. Restart the server

I will add this to the documentation

**Comment by harshithmullapudi** [comment]
We are working on bringing in a local model, that's something we will be picking this week.

**Comment by ashish07-07** [comment]
> Hey, do you see any error in the server you can use this command `docker logs <server-id>`. We use OpenAI to generate the titles https://platform.openai.com/docs/quickstart/account-setup can you use this to generate a key. Once you generate
> 
> 1. Add it to the .env
> 2. Restart the server
> 
> I will add this to the documentation

I guess we cant use the gpt's api key for free , like we need to buy credits for using it . But the Gemini api keys are free and anyone  can use it for free.

**Comment by harshithmullapudi** [comment]
Hey @ashish07-07 we have added support to fallback to a local modal so that we won't depend on OpenAI. You can try using it now. Let us know if you face any problems
