### ISSUE TITLE
Incorrect Status Order When Changing Issue Status

### ISSUE THREAD

**Issue by vedartm** [tegonhq/tegon#159]
While changing the status of an issue, the order of the status does not seem to be right.

![Screenshot 2024-07-30 at 9 27 43 PM](https://github.com/user-attachments/assets/9fa5ebeb-5134-4fcd-b0e4-c5e6f0cda3de)

The order is 

1. Backlog
2. Todo
3. In progress
4. ...

**Comment by AggManik** [comment]
Hi @vedartm - thanks for flagging this out. We'll let you once this is fixed.

**Comment by AggManik** [comment]
This is fixed
