### ISSUE TITLE
Logging: Advance Logging Support

### ISSUE THREAD

**Issue by mrchocha** [tegonhq/tegon#201]
## Context

Currently tegon is using nestjs inbuilt logger which might not be helpful in future since it lacks multiple details related to application specific logic i.e. tenant info, request info, etc.

In-future if we connect tegon with tools like elasticsearch for logging and debugging this info will be necessary.

## Proposed Solution

There can be a custom logger class which will override the current logger and log the necessary info.

### Schema and New Logging Style

New logger will take following parameters in input i.e.

```typescript
interface LoggerInput {
  message: string; // log message
  payload?: Record<string, any>; // different parameters
  where?: string; // function/method name where the log is added
}
```

The logging will look something like this

```typescript
this.logger.info({
  message: "Created New issue",
  payload: { issueId: "abc" },
  where: "IssueService.createNewIssue",
});
```

### Actual Logging in Background

Following fields should be logged in console and log file

```typescript
interface LogInfo {
  timeStamp: string; // log timestamp
  message: string; // log message
  payload?: Record<string, any>; // different parameters
  where?: string; // function/method name where the log is added
  workspaceId: string; // request workspaceId
  userId: string; // userId of current request context
  opName?: string; // operation or endpoint name from where the request was initiated
  requestId: string;
  level: string; // log level
}
```

\*\* Here to get requestId, userId, workspaceId (current request context) we can use `AsyncLocalStorage`

following is the library we can use to achieve above goal.
https://www.npmjs.com/package/nest-winston

**Comment by saimanoj** [comment]
Closed with [213](https://github.com/tegonhq/tegon/pull/213)
