### ISSUE TITLE
Add steps in self hosting documentation 

### ISSUE THREAD

**Issue by sane5ek** [tegonhq/tegon#257]
it is not described here that logging into the application after deployment requires users to enter an email to send a letter. And it also does not describe which variables and where need to be set for SMTP (and that SMTP is needed at all). Please correct  
  
Also, after installing SMTP, logging in via the link in the email does not work. Requests /api/v1/users and /api/auth/session/refresh return 401, after which the user is immediately logged out  
  
Reference - [https://github.com/tegonhq/tegon/issues/257](https://github.com/tegonhq/tegon/issues/257)

**Comment by AdityaSanthosh** [comment]
#280 #281

**Comment by AggManik** [comment]
Hey @sane5ek we have updated the docs, were you able to setup up tegon locally or in self-hosting environment?
