### ISSUE TITLE
Self host user invite not working

### ISSUE THREAD

**Issue by PravinRajnale** [tegonhq/tegon#263]
When attempting to invite users to the self-hosted instance, the invite functionality is not working. The system fails to send the invitation email or add the new user to the system. This issue blocks the ability to link new users effectively. PFA the attached screenshot.

Error: "Invites failed, Try again after sometime: forbidden resource"
![IMG-20240924-WA0014](https://github.com/user-attachments/assets/14191f7e-be7e-4a3f-8bd0-9fb06ed0dafb)

**Comment by saimanoj** [comment]
hey @PravinRajnale, can you pull the latest docker image version 0.3.6-alpha of the server and webapp. logout and login again.  let me know if it doesn't work. 

Also, if you don't set smtp it won't send an invite email to that user. it'll just create a row in the invite table.

**Comment by AggManik** [comment]
Hey @PravinRajnale did it work?

**Comment by PravinRajnale** [comment]
I tried troubleshooting/debugging it locally but the error seems to be unresolved. PFA
![IMG-20241002-WA0001](https://github.com/user-attachments/assets/2c3e1d9d-c9a9-4006-b10c-8931321172fe)
![IMG-20241002-WA0000](https://github.com/user-attachments/assets/a2deb52b-9f73-4e92-b15e-e711b1677a1d)

**Comment by saimanoj** [comment]
@PravinRajnale, can you also copy `.env` to apps/server to run `pnpm migrate`. 

webapp is not able to connect server. can you also share server logs?

**Comment by PravinRajnale** [comment]
Can you please check these screenshots, when i tried to run apps/server - run pnpm migrate - i am getting server not found. 

![IMG-20241002-WA0028](https://github.com/user-attachments/assets/c986efe8-8e22-4d62-b897-1936bed39da6)
![IMG-20241002-WA0029](https://github.com/user-attachments/assets/a4f85aad-993f-4794-9f67-d2c5b0d753db)
![IMG-20241002-WA0030](https://github.com/user-attachments/assets/289e66ba-dd9a-4130-859f-7cd15e312cad)

**Comment by saimanoj** [comment]
please change DB_HOST to localhost.

Also, is the Docker environment possibly mixed with the local setup?

**Comment by PravinRajnale** [comment]
when i run pnpm migrate in app/server is migrating but when i run docker-compose/route error"database not found/ prisma can't connect" PFA the screenshot. 
![image (2)](https://github.com/user-attachments/assets/a9fbf0fb-95ef-4901-86c3-c335aeaacd4c)
![image (3)](https://github.com/user-attachments/assets/c7b0b5c1-1443-4347-b395-0f90e4d72fa5)

**Comment by saimanoj** [comment]
@PravinRajnale can you please check if the .env file is set up correctly in the docker-compose directory?

**Comment by AdityaSanthosh** [comment]
@PravinRajnale  Can you look at the updated [local setup](https://docs.tegon.ai/oss/local-setup) instructions and retry?
