### ISSUE TITLE
Fix: sidebar button is hidden in inbox view when the sidebar is hidden

### ISSUE THREAD

**Issue by vikulikov** [tegonhq/tegon#296]
<img width="1532" alt="image" src="https://github.com/user-attachments/assets/f443ca67-6cc7-4544-9713-65ebf14ddd3f">

**Comment by AggManik** [comment]
Hey @vikulikov thanks for spotting this up. I was able to reproduce it. We will let you know once it is fixed.

**Comment by skdishansachin** [comment]
I have the same problem. If no one has started on it yet, I would like to work on it.
