### ISSUE TITLE
Having trouble setting up the project locally

### ISSUE THREAD

**Issue by skdishansachin** [tegonhq/tegon#308]
I followed the local setup section of the [docs](https://docs.tegon.ai/oss/local-setup#cloning-the-tegon-repository), but the installation process encountered an issue. I ran the `pnpm dev` command, and it successfully started the application.

I got an error on  (#297) -

```
⨯ ./src/pages/_app.tsx:2:0
│ Module not found: Can't resolve '@tegonhq/ui/index.css'
│   1 | import './global.css';
│ > 2 | import '@tegonhq/ui/index.css';
│   3 | import '@tegonhq/ui/global.css';
│   4 | import type { NextComponentType } from 'next';
│   5 | import type { AppContext, AppInitialProps, AppLayoutProps } from 'next/app';
```

I appreciate any help.

**Comment by harshithmullapudi** [comment]
Hey ideally this should be generated from the `packages/ui` package and which is what we import. Could you check if that file is generated you can move between the shells using arrow keys when you run `pnpm dev`

**Comment by skdishansachin** [comment]
I checked for the file, but it's not available. Do you have any ideas on how to make it work? If you need more information from my end, please let me know.

**Comment by harshithmullapudi** [comment]
In a new terminal session you can go to `packages/ui` folder and run `pnpm generate`. Also could you share the screenshot of the `pnpm dev` command?

**Comment by skdishansachin** [comment]
Running the `pnpm dev` command solved the issue, but now I have a problem with CORS.

**Comment by skdishansachin** [comment]
Here are the errors related to CORS. I would appreciate any help.

```
Access to fetch at 'http://localhost:3000/api/auth/session/refresh' from origin 'http://127.0.0.1:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

POST http://localhost:3000/api/auth/session/refresh net::ERR_FAILED

Access to fetch at 'http://localhost:3000/api/auth/signinup/code' from origin 'http://127.0.0.1:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

POST http://localhost:3000/api/auth/signinup/code net::ERR_FAILED
```

**Comment by harshithmullapudi** [comment]
you are accessing at which URL ? Ideally CORS shouldn't happen because the webapp and server are at same domain. 
webapp: `http://localhost:3000`
server: `http://localhost:3000/api`

**Comment by harshithmullapudi** [comment]
Sorry for late response. Can you join the slack channel we can debug there?

**Comment by skdishansachin** [comment]
Sure, the issue will be closed as the conversation continues on Slack.
