### ISSUE TITLE
Video on home page gives 404

### ISSUE THREAD

**Issue by jpinnix** [tegonhq/tegon#64]
![image](https://github.com/tegonhq/tegon/assets/4436/4a5d358d-6009-4172-8e8e-943dd0446267)

**Comment by qu8n** [comment]
This video was taken down intentionally due to backlash on Tegon directly copying Linear's UI. See [this Twitter thread](https://twitter.com/thisritchie/status/1788527859952238598) for some context.

**Comment by harshithmullapudi** [comment]
Yeah we will get back once we change the UI.
