### ISSUE TITLE
It is Open-source, then where is docs for self-hosting?

### ISSUE THREAD

**Issue by yesbhautik** [tegonhq/tegon#70]
— no much information available on the Website— There is no any clear information for self-hosting, configurations and features— [Signup ](https://app.tegon.ai/auth/signup)not working, how we can check the product!

![image](https://github.com/tegonhq/tegon/assets/63995315/a9b85e96-dbf1-4dbc-aa6e-d9bb95a10678)

**Comment by harshithmullapudi** [comment]
Hey, we haven't opened the cloud for everyone so we don't yet have a signup option. We are working on the documentation and should be there in the next few days. We will update here. 

Thank you for your patience.

**Comment by harshithmullapudi** [comment]
Yeah sure, once we have v0 of the doc would love if we can get help in making that better.

**Comment by yesbhautik** [comment]
> Yeah sure, once we have v0 of the doc would love if we can get help in making that better.

Can we talk on chat to discuss further!

**Comment by harshithmullapudi** [comment]
Sure, we can speak on [Slack](https://join.slack.com/t/tegoncommunity/shared_invite/zt-2i1e781ip-zwauijRV9TRtRKoJi3tqng).

**Comment by yesbhautik** [comment]
> Sure, we can speak on [Slack](https://join.slack.com/t/tegoncommunity/shared_invite/zt-2i1e781ip-zwauijRV9TRtRKoJi3tqng).

cool
