### ISSUE TITLE
Issue: Slack Invite link not working

### ISSUE THREAD

**Issue by mrchocha** [tegonhq/tegon#82]
<img width="859" alt="image" src="https://github.com/tegonhq/tegon/assets/49686817/41d48295-eb0c-4afa-bf2a-d2b8eec5e065">

**Comment by AggManik** [comment]
Hey thanks for informing. It got expired and I have updated it. You can join now using this link: https://join.slack.com/t/tegoncommunity/shared_invite/zt-2jvar8p1x-9wqFTL9PP5ICImb76qcjEA

**Comment by mrchocha** [comment]
Working now, Thanks!
