### ISSUE TITLE
What happens if internet/socket disconnects and changes are made

### ISSUE THREAD

**Issue by abiodunooni** [tegonhq/tegon#89]
Hello Team,

Projects looks really great.
Noticed however that there is no support for syncing changes made by a user when they were offline once they reconnect.

Perhaps a handler for socket reconnection that fetches the lastsequenceid from the server and cross checks with what's in localstorage to know just out of date it's data is, then pulls the delta.

(not sure how to then handle updating the server with changes made locally, or handling conflicts. Perhaps a change queue that's stored locally? 🤷‍♂️)

**Comment by saimanoj** [comment]
Hi, we're aware that offline changes are not currently updating on the server. As you've mentioned, we're planning to address this with a queuing system in local and conflict resolution mechanisms to ensure data consistency. 

we'll implement it soon.

**Comment by saimanoj** [comment]
Hi, we're aware that offline changes are not currently updating on the server. As you've mentioned, we're planning to address this with a queuing system in local and conflict resolution mechanisms to ensure data consistency.

we'll implement it soon.

**Comment by abiodunooni** [comment]
Awesome!
Will this also include support for optimistic updates? 
Noticed that the API latency is quite high 7 - 10sec to create an issue

**Comment by harshithmullapudi** [comment]
yeah, currently there are some stuff happening when issue is created thus the latency we will work on that to reduce it.
